environment = bcvaxdevit
test_rail   = yes

########################################################################################################################
# BCVAXDEVIT - DEV

bcvaxdevit.testrail_run_id = 4038
bcvaxdevit.url             = https://bcphsa--bcvaxdevit.my.salesforce.com/
preview.user0              = TESTERBASCAUTO
preview.password0          = password


########################################################################################################################
# BCVAXUAT - TEST

bcvaxuat.testrail_run_id    = 1754
accept01.url                = https://ubw-accept01.unit4cloud.com/ca_bcc_acpt_web/Login/Login.aspx
accept01.user0              = TSTBAAUTO
accept01.password0          = password

########################################################################################################################
# PRODSUPQA = PROD Support

prodsupqa.testrail_run_id   = 1755
prodsupqa.url               = https://ubw-accept02.unit4cloud.com/ca_bcc_acpt02_web/Login/Login.aspx
prodsupqa.user0             = RSTRATOV
prodsupqa.password0         = RSTRATOV

########################################################################################################################